### ISSUE TITLE
Release on WebJars

### ISSUE THREAD

**Issue by paulbutcher** [flesler/jquery.scrollTo#100]
It would be really helpful if jquery.scrollTo was available on WebJars:

http://www.webjars.org

(we're working on an application written in a combination of Clojure and ClojureScript, built with Leiningen. None of bower, npm or composer are particularly convenient to use from Leiningen. Right now, the only third-party JS library we're using that isn't on WebJars is jquery.scrollTo :-)

Thanks!

**Comment by flesler** [comment]
Hi @paulbutcher still interested in this? else I'll close

**Comment by paulbutcher** [comment]
It would still be nice, but (obviously!) not something I've been able to find time to look at, so feel free to close.
