### ISSUE TITLE
How to add a "snap to" for touch devices

### ISSUE THREAD

**Issue by coldes** [flesler/jquery.scrollTo#106]
Is there a way to add a "snap to" for touch devices when swiping/scrolling?

**Comment by flesler** [comment]
Could you describe that funcionality?

**Comment by coldes** [comment]
...I will explain this way, I have come across 2 different scroll plugins, am going with yours as I can create/ assign an onclick nav to scroll direct to a horizontal page, however using a swipe gesture whether track pad or touch swipe, your plugin is a continuous scroll, where this plugin link below has a snap to threshold when swiping/scrolling from page to page, each snaps to the viewport
[https://github.com/trgraglia/jquery.horizonScroll.js]
Hope this makes sense

**Comment by flesler** [comment]
I see, is there a way I can see that behavior working?
Else, would you provide the call to that plugin with the right settings to reproduce it?

**Comment by coldes** [comment]
...basically I am after the same effect that can be seen when swiping between home screen pages on an ipad/iphone

[I also just discovered first hand, as well as seeing it as an issue on your github, how your plugin is not working in the latest Chrome Browser for Android - I believe this is an issue with Chrome as the plugin works every else]

Depending how the above description works for you I will setup in the next day or so a basic website scenario to assist

**Comment by flesler** [comment]
I don't think there's a bug report for Chrome Android specifically, there are 2 for Chrome 40 as a whole. There's a beta version on a [branch](https://github.com/flesler/jquery.scrollTo/tree/window-scroll) that handles Chrome 40 correctly, it has been tested on desktops and iOS but not on Android (if you can then great).

**Comment by flesler** [comment]
I've checked the demo (in a desktop mind you) at http://trgraglia.github.io/jquery.horizonScroll.js/demo/index.html
Still not sure what you mean by snapping, do you mean easing?

**Comment by coldes** [comment]
fyi - the link below is the original framework I came across - I have updated it to the latest version of your plugin and running jquery 1.11.2 - I should have sent you this first off as you will see, run "DEMO 2", the page nav links on click "snap" each page into place. Using touch swipe or mouse/trackpad scroll, the pages are a continuous scroll. What I think would be really good is the "snap to" also happens when using touch swipe/mouse/trackpad scroll. I am presuming modifying either of your 2 scripts, "jquery.scrollTo" and "jquery.localScroll" would acheive this "snap to" outcome

Link to framework page [http://www.websitecodetutorials.com/code/jquery-plugins/horizontal-website.php]

Link to newer "jquery.scrollTo" and "jquery.localScroll"
[https://dl.dropboxusercontent.com/u/7494446/misc/horizontal-scroll.js]

Hope this make better sense now, and if you feel this is achievable then fantastic

thank you

**Comment by flesler** [comment]
So... the demo is simply both scroll plugins and changing the default axis to 'x'.
I don't see any new feature needed.

Certainly your demo required some CSS and whatnot, but I still don't see what you'd like to add to the plugin.
Certainly the whole touch/trackpad part should be added outside the plugin as it's surely of its scope.
It could make sense to also add jquery.serialScroll to that page for sequential navigation, that plugin exposes a simple way to make it jump to the next slide. So it should be easy to add the touch scrolling using serialScroll. Note that localScroll plays nicely with it so you can keep the anchor navigation and both will interact.

**Comment by coldes** [comment]
...thanks for the reply
