### ISSUE TITLE
Try using animate+step+window.scrollTo/$().scrollTop()

### ISSUE THREAD

**Issue by flesler** [flesler/jquery.scrollTo#107]
Found some alternative approaches mentioned on [StackOverflow](https://stackoverflow.com/questions/4034659/is-it-possible-to-animate-scrolltop-with-jquery/) linked by @westurner in [here](https://github.com/flesler/jquery.scrollTo/issues/67#issuecomment-62344246).

It could be an alternative solution to all the _scrollable() feature detection.

**Comment by flesler** [comment]
Done, I will merge the tests with those from #101 so both approaches can be compared

**Comment by flesler** [comment]
Added [tests](http://flesler.github.io/jquery.scrollTo/tests2/) from this branch side by side to `window-scroll` branch.

**Comment by flesler** [comment]
I decided that if this alternative was to prevail, it should be 2.0.0 rather than 1.5.0 because it's even less backwards-compatible than the other option and it contains a highly requested and powerful feature.

**Comment by npetrovski** [comment]
For branch window-scroll-alt :
=====================================
FF 36.0 - OK
IE 11.0.9600.17633 - OK
Chrome 40.0.2214.93 - OK
Safari for PC 5.1.7 (75.57.2) - OK
Android FF 37.0 - OK
Android Chrome 40.0.2214.109 - OK
=====================================

Congratz - wrap it in 2.0.0 :-)

**Comment by markvantilburg** [comment]
Windows Phone 8.1:

These do not animate:
Max window scrolling, within an iframe (compat mode)
Max window scrolling, within an iframe (quirks mode)
Max iframe scrolling from outside (compat mode)
Max iframe scrolling from outside (quirks mode)

In the old version they did animate but not always, depending on when what was loaded.

![200-wp81](https://cloud.githubusercontent.com/assets/4510245/6516545/278fbc54-c393-11e4-9130-283e96c3593a.png)

![200-wp81-desktop](https://cloud.githubusercontent.com/assets/4510245/6516546/2aee9938-c393-11e4-807d-f46b2a673e4c.png)

**Comment by flesler** [comment]
Ok, I'm less concerned about the iframe cases honestly, they are rare. It could be due to a bad test implementation it's not top quality.
Do you know when did those iframe tests failed on the 1.5.0 version? I'd like to try and fix it if really a bug on the test.

**Comment by markvantilburg** [comment]
It has to do with timing i guess. When i select the iframe and refresh only that the scrolling happens. Otherwise it's just puts the "agent information" instantly.

**Comment by flesler** [comment]
Same happens with 2.0.0 or that one never works at all?

**Comment by markvantilburg** [comment]
In the 2.0.0 nothing happens on the iframe pages. The old 1.5 did only fire if i refresh the iframe myself.

**Comment by flesler** [comment]
Windows 7
Firefox 36.0.1 - ALL OK
Chrome 41.0.2272.76 - ALL OK
IE 10.0.9200.16750 - ALL OK

**Comment by flesler** [comment]
iPhone 4S
Chrome 40.0.2214.73 - ALL OK except iframes 
Safari (not sure where's the version) - ALL OK except iframes

I think the iframes don't work just because the tests are not rendered correctly on these browsers, the iframe is full height without overflow. I did a few changes but still no luck, I don't worry much about it honestly.

**Comment by flesler** [comment]
Mac OSX Yosemite 10.10.1
Chrome 41.0.2272.89 - ALL OK
Safari 8.0 - ALL OK

**Comment by flesler** [comment]
I'd really like to release this as 2.0.0, was hoping more people were going to test it.
I might release it and if any issue arises fix it for 2.0.1.
Considering it's a major version bump complete backwards compatibility shouldn't be expected anyway.

**Comment by flesler** [comment]
I merged 2.0.0 to master via #107.
If you have any issue after the update, first check [this link](https://github.com/flesler/jquery.scrollTo/wiki/Migrating-to-2.0), If your problem is not solved then go ahead and [report the issue](https://github.com/flesler/jquery.scrollTo/issues/new).
