### ISSUE TITLE
New version breaks localScroll

### ISSUE THREAD

**Issue by philwareham** [flesler/jquery.scrollTo#110]
I use this in conjunction with your [localScroll](https://github.com/flesler/jquery.localScroll) plugin. However version 2.x seems to break it. Can you confirm?

**Comment by flesler** [comment]
Hi,
It's possible, if so I'll work on a fix asap.
Can you provide more details on the problem? any error on console?

**Comment by flesler** [comment]
Ok just detected the problem myself, will fix asap.

**Comment by flesler** [comment]
Done, update to localScroll 1.4.0. Let me know if you find any issue
Thanks for reporting

**Comment by philwareham** [comment]
Thanks!
