### ISSUE TITLE
 Use custom events, instead the callbacks

### ISSUE THREAD

**Issue by klihelp** [flesler/jquery.scrollTo#112]
Triggering custom events gives more flexibility.
Current workaround:
```
onBefore:function( e, anchor, $target ){

	$(document).trigger('scrollTo:onBefore', [e, anchor, $target])

},
onAfter:function( anchor, settings ){

	$(document).trigger('scrollTo:onAfter', [anchor, settings])
}
```

**Comment by flesler** [comment]
It's a fine proposal, both approaches are ok. The thing is this plugin tries to mimic $().animate() API and behavior. Also, it seems wasteful to build an event system on top of the callback system one must use when interacting with $().animate().

Thanks for the proposal but this will remain as it is.
