### ISSUE TITLE
jquery.scrollTo animation not always working

### ISSUE THREAD

**Issue by celron** [flesler/jquery.scrollTo#113]
Greetings,
I'm using your plugin to great effect.  It works fine in a majority of cases, and scrolls as desired.  

However in one use case, on iOS iPad using Cordova, the animation does not correctly happen.  In the first image, you can see what happens initially, and in the second if I press or execute scrollTo again.

In a browsers, on Windows, macOs, android  and iOS, the scrolling seems to work correctly, and on other devices, scrolling occurs horizontally rather than vertically, and there are no problems.

I am using the latest version of scrollTo (1.2.1) with jquery 2.1.3 and jquery mobile 1.4.5.  Because this problem is very specific, and works in all other cases, I'm pretty sure the problem is not in scrollTo, and I'm hoping that you might be able to point me in a direction for resolution.

I've tried different ways of forcing redraws, timers to call it scrollTo() even calling $(window).trigger('resize'); to no avail.  

![img_0292](https://cloud.githubusercontent.com/assets/7539817/7597355/fc7113ca-f8c0-11e4-9bd4-0cb40c16ad7f.PNG)
![img_0293](https://cloud.githubusercontent.com/assets/7539817/7597356/fc75bf06-f8c0-11e4-8bcd-91fe6dbb1ff4.PNG)

**Comment by flesler** [comment]
Hi, first of all, latest version of scrollTo is 2.1.1, I assume that was what you meant.
I don't quite understand the issue by seeing the 2 screenshots, do you think you could make a small jsfiddle where the problem happens?

Most issues with scrollTo are actually due to the CSS (and in some cases the HTML). One thing you could do is change the overflow:hidden to auto make sure the element that you're trying to scroll has the scrollbar you'd expect. If you can't do that manually with a scrollbar, the DOM won't scroll when called via JS.

**Comment by celron** [comment]
Sorry you are correct it is 2.1.1.

What happens is that when you click on the markers on the map (ie Koliba Restaurant) the left hand side is suppose to scroll (using scrollTo) to the entry and highlight it which you don't see in the first screen-shot.  Clicking on the marker a second time causes it to display, so I believe it might have to have something to do with a redraw not happening.

There is no problem in scrolling on the left-hand side (there are up to 20 entries) and clicking (touch actually) on an entry; you can move to different entries and the marker infowindow will appear when you click on it (ie pressing the entry on okeanos will cause the corresponding marker on the map to 'popup'.

I will try to put together a testcase in jsfiddle, however I'm somewhat sure it won't show the problem because it only happens on iOS in Cordova, so this is not something happening in a normal browser.  I have tested this on a pc with firefox and safari, a mac using safari and chrome and do not see the problem.  I can see if it occurs in a browser on an ipad.

**Comment by celron** [comment]
I have a testcase, however it does not show the problem, and works fine on windows, mac os and ios.  Everything scrolls and works the way it's suppose to.

http://jsfiddle.net/telhar/3x8gzwzd/
What happens in Cordova is that when you click on one of the buttons on the right, the left (or part of it) goes blank, until you click on the button again or over the unpainted area, it will refresh the page

**Comment by celron** [comment]
Greetings,
I believe that you ca

**Comment by celron** [comment]
It appears that the sequence of execution has less to do with the problem than if -webkit-overflow-scrolling: trouch is in use.  The problem occurs less with the sequence but removing this seems to remove the problem.
Hopefully this posting will help someone else who might encounter the same problem.

**Comment by flesler** [comment]
Thanks for the final comment, I'm glad you worked that out

**Comment by tylerwiegand** [comment]
having a very similar problem. added a few iterations of attempted fixes to this, but...

JS:
$('a[href^="#"]').click(function(e) {
		e.preventDefault();
		$(window).stop(true).scrollTo(this.hash, {duration:1000, interrupt:true, onAfter: $(this.hash).toggleClass("testclass")});
	});

CSS:
.testclass {
	background-color: #8b1e7d !important;
	-webkit-overflow-scrolling: auto !important;
	-webkit-transform: translate3d(0,0,0) !important;
}

it styles the class with the background color (to try to fix this issue...) but when i click mah buttons on MOBILE SAFARI ONLY (8.4 just updated yesterday on iPhone 5s) it starts moving a tiny tiny bit and styles the class accordingly on the targetted this.hash but...doesnt continue moving. tried it with and without the webkit-overflow and webkit-transform...It works BEAUTIFULLY on every other browser in every device...but mobile safari is a huge userbase so...=\

Any ideas ?

**Comment by flesler** [comment]
The `onAfter` setting expect a function, you're executing it in-place.
It's not a bug. For support you should rather ask this on a forum like StackOverflow where more people will look at it, Github issues are for bugs and feature requests.

Thanks

**Comment by tylerwiegand** [comment]
Thanks! Sorry, new at this. I gave up and just pointed directly at each link in any case for now. In the future I will follow your suggestion which I take as the culturally accepted method =)

-Tyler
