### ISSUE TITLE
Cannot read property 'propHooks' of undefined

### ISSUE THREAD

**Issue by gpapin** [flesler/jquery.scrollTo#115]
I have an issue when loading the plugin, I've got the following error :
```Cannot read property 'propHooks' of undefined```

```
	// Add special hooks so that window scroll properties can be animated
	$.Tween.propHooks.scrollLeft =    <--------------- It complain about this line
	$.Tween.propHooks.scrollTop = {
		get: function(t) {
			return $(t.elem)[t.prop]();
		},
		set: function(t) {
			var curr = this.get(t);
			// If interrupt is true and user scrolled, stop animating
			if (t.options.interrupt && t._last && t._last !== curr) {
				return $(t.elem).stop();
			}
			var next = Math.round(t.now);
			// Don't waste CPU
			// Browsers don't render floating point scroll
			if (curr !== next) {
				$(t.elem)[t.prop](next);
				t._last = this.get(t);
			}
		}
	};

```

**Comment by flesler** [comment]
Hi, the plugin requires at least jQuery 1.8. Are you using an older version?
I should specify that in the README (it's in the JSONs but still)

**Comment by gpapin** [comment]
Thanks you very much for the prompt reply (and the awesome plugin), now I have to update jQuery and I make sure I don't break everything :smile:

**Comment by BrianCohen** [comment]
I happens with JQuery 3.1.1

**Comment by kevinwarren** [comment]
Same with me. I'm using jQuery 3.2.1

**Comment by kevinwarren** [comment]
LOL I've figured it out.

Use the full jQuery version not the slim version!

The slim version doesn't have the $.animate function.

**Comment by VadimGouskov** [comment]
Thanks @kevinwarren, I made the same mistake.

**Comment by soliniak** [comment]
Years go by and people (me) keep making this mistake :D

**Comment by Rostyslav27** [comment]
> LOL I've figured it out.
> 
> Use the full jQuery version not the slim version!
> 
> The slim version doesn't have the $.animate function.

how to do that?

does 'npm i jquery' install full version?
