### ISSUE TITLE
Scrolls to wrong position if scroll width/height updates while animating

### ISSUE THREAD

**Issue by jaydenseric** [flesler/jquery.scrollTo#117]
A container is scrolled to the wrong position if it's `scrollWidth` or `scrollHeight` updates while animating.

There are lots of occasions this is an issue; the most common is when you attempt to scroll the page to an element (on document ready) while the page is still loading and growing in height.

I use scrollTo almost exclusively as part of our client-side URL hash routing. It works fine when the hash route changes after page load, but if you use a route for a fresh load you get scrolled to random parts of the document.

To see this happening in a real situation:

1. Visit [http://allnewmazdamx5.com.au/#/section/skyactiv-technology](http://allnewmazdamx5.com.au/#/section/skyactiv-technology). If you are on an average internet connection, you will probably be scrolled to an incorrect location on the page.
2. Press enter in the URL bar to trigger the hash again, without reloading the page. It should take you to the exact position intended.

The solution is to store original `scrollHeight` of the container being scrolled at the start of the animation. For every animation frame check if the `scrollHeight` is still the same (not as expensive as it sounds). If it is not, cancel the current animation and calculate a fresh one to cover the new distance. In the same way you will need to handle the x-axis using `scrollWidth`.

I have used this solution effectively in the past in my own custom scrollTo plugin.

**Comment by jaydenseric** [comment]
In the mean time, here is a way around the problem:

```js
function scrollPageTo($target) {
  var scrollHeight = document.body.scrollHeight;
  $(window).stop(true).scrollTo($target, {
    duration: 600,
    progress: function() {
      // If the page scroll height changes, scroll afresh to the shifted target
      if (scrollHeight !== document.body.scrollHeight) scrollPageTo($target);
    }
  });
}

// Document ready
$(function() {
    scrollPageTo($('#id-of-element'));
});
```

**Comment by flesler** [comment]
Hi @jaydenseric,

This is a shared problem among all the uses of $().animate(), rather than solving it within the plugin for the 1000th time, I prefer if people either use a custom solution or maybe come out with a plugin that solves all at once. Else we're all solving the same problems.

Regards
