### ISSUE TITLE
TypeError: $(...).ScrollTo is not a function

### ISSUE THREAD

**Issue by joe-liquid** [flesler/jquery.scrollTo#119]
I am getting the following in Firefox on the latest release. I am on jQuery 1.11.0. I can see jQuery is loaded. 

TypeError: $(...).ScrollTo is not a function

**Comment by flesler** [comment]
It's `$(...).scrollTo()`, with lower case "s"

**Comment by AndrewKiri** [comment]
Having the same problem with no clue what's wrong. Here are the screen captures
![image](https://cloud.githubusercontent.com/assets/13384229/24101840/1be506ba-0d7a-11e7-92f4-c159f710630d.png)
![image](https://cloud.githubusercontent.com/assets/13384229/24101854/278d1db8-0d7a-11e7-91a9-abe1d953e4ae.png)
checked the target var, it is ok and returns a jQuery dom el
