### ISSUE TITLE
Uncaught TypeError: Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by pestka** [flesler/jquery.scrollTo#121]
Script gives this error if target does not exist.

**Comment by flesler** [comment]
You mean if target is `null`? That's not a valid value to be passed to the plugin.
It does support an empty jQuery object so it doesn't break when used on several pages, but passing `null` or `undefined` makes no sense.

Could you describe the situation? thanks

**Comment by pestka** [comment]
Thanks for quick response.
Just pass a jquery object with selector that gives empty jquery set, ex:
<pre>$.scrollTo($("doesnotexist"));</pre>

**Comment by flesler** [comment]
You were right, it was handled when passing a selector but not jQuery object, it now is. Can you download 2.1.2 and confirm it's fixed?
Thanks

**Comment by pestka** [comment]
Yep, it's fixed in 2.1.2.
Great job!
