### ISSUE TITLE
How to scroll to a target element but only if the direction is down?

### ISSUE THREAD

**Issue by u01jmg3** [flesler/jquery.scrollTo#124]
- How can you scroll to a target element but only do this if the scroll direction is downwards?

**Comment by flesler** [comment]
You should ask these questions on sites like StackOverflow, there are many more people available there. Github issues are only for bug/feature/enhancement requests.

Regards

**Comment by u01jmg3** [comment]
But it's a question about using your library? I'm asking whether this is possible with your library. Or if you have any insight into how this can be achieved? If the answer is 'no' then this ticket could lead onto an enhancement request.

Asking the author of the plugin I have a question about seems far more logical than asking a community of people who may or may not have experience of using your plugin.

**Comment by u01jmg3** [comment]
So far I have achieved this with the following but I wasn't sure whether I'd missed an option in your plugin which I why I opened this ticket:

```js
if($('.target').offset().top > $(window).scrollTop()){
    // Action
}
```
