### ISSUE TITLE
How to scroll to the bottom of a target element but only as far as not to scroll the top out of view?

### ISSUE THREAD

**Issue by u01jmg3** [flesler/jquery.scrollTo#125]
- How to scroll to the bottom of a target element but only as far as not to scroll the top of the element out of view?
  - Basically a "try and scroll this whole div into view but only as far as not hiding the top of it" scenario.

**Comment by flesler** [comment]
You should ask these questions on sites like StackOverflow, there are many more people available there. Github issues are only for bug/feature/enhancement requests.

Regards

**Comment by u01jmg3** [comment]
But it's a question about using your library? I'm asking whether this is possible with your library. Or if you have any insight into how this can be achieved? If the answer is 'no' then this ticket could lead onto an enhancement request.

Asking the author of the plugin I have a question about seems far more logical than asking a community of people who may or may not have experience of using your plugin.
