### ISSUE TITLE
Scroll Down when Mobile Connect

### ISSUE THREAD

**Issue by sidaurukfreddy** [flesler/jquery.scrollTo#126]
Hi quick question how can i make scroll down when mobile acsess my website ?
should i use width to detect mobile device or what, need suggestion, 

Thanks

**Comment by flesler** [comment]
Are you referring to that trick to hide the top bar? If so, I think it's just:
```js
window.scrollTo(0, 1);
```
No need for this plugin.
If you need to detect mobile, you should search for a plugin that handles that., I don't know any sadly.

**Comment by sidaurukfreddy** [comment]
Wait sorry for comment again, so is not possible to detect by get width in jquery ?
pelase hit this likn http://codepen.io/sidaurukfreddy/pen/MaZwoP

please click button then will show another div in the right in the desktop but mobile like i said above, so what the best way your advice to handle my issue?

Thanks bro
