### ISSUE TITLE
Uncaught Error: Syntax error, unrecognized expression

### ISSUE THREAD

**Issue by AndrewLag** [flesler/jquery.scrollTo#127]
Hallo, I tried to insert the scroll code into the footer.php of a wordpress site.
First of all I had to change the dollar sign with jQuery, because of conflict problem. The problem seems to reman, though.

The code in the attachment:
[footer.txt](https://github.com/flesler/jquery.scrollTo/files/36878/footer.txt)

**Comment by flesler** [comment]
You should inspect what are you passing to the plugin, in other words, what's in the `href` variable.
```js
console.log(href); // or alert(href)
```
You could try to replace:
```js
var href = jQuery(this).attr('href');
```
for
```js
var href = this.hash;
```

**Comment by AndrewLag** [comment]
The var href is "http://mywebsite.com/#real-title" ... it seems ok but it comes that error.
