### ISSUE TITLE
overflow:auto breaks scrollTo?

### ISSUE THREAD

**Issue by BlackSkorpio** [flesler/jquery.scrollTo#128]
I have added overflow:auto to the container that surrounds everything (to ensure that my menu is scrollable on touch devices) and this seams to break scrollTo, since I no longer is scrolled!
You can see the behavior here: http://kokensupport.varoystrand.se/DEV/content/

Removing overflow:auto from the main() and scrollTo works as expected.

**Comment by travislaynewilson** [comment]
I'm also having issues with this. I've confirmed that @BlackSkorpio is correct.

**Comment by flesler** [comment]
Hi sorry for the delay, scrollTo should work everywhere a scrollbar would show.
Set overflow auto to the inner element, the one you intent scrollTo to work. If it doesn't show a scrollbar, then that needs to be fixed using CSS in some way.
