### ISSUE TITLE
interrupt not working properly with native smooth scrolling

### ISSUE THREAD

**Issue by dwelle** [flesler/jquery.scrollTo#131]
Setting `interrupt: true` doesn't work very well for browsers with native smooth scrolling (FF, Chrome v49/50). It requires the user to scroll multiple times (meaning you must scroll like crazy to interrupt). This is more pronounced in Chrome (Canary 49/50, not sure when they added smooth scrolling exactly) where it's nearly impossible to interrupt.

scrollTo `v2.1.2`

**Comment by flesler** [comment]
It might be a tricky one, will try to check this out asap.
If you figure out a solution and can provide a PR, I'll validate and merge

**Comment by dwelle** [comment]
Not really sure how. Would have to get into how the jQuery tweening is implemented. Right now I just hacked it by adding a `wheel` event, which is in no way complete solution.

**Comment by flesler** [comment]
Closing for the PR
