### ISSUE TITLE
Don't scroll if element is already visible (optional behaviour)

### ISSUE THREAD

**Issue by dmak** [flesler/jquery.scrollTo#136]
Actually this is a new feature request.

Would be nice to have an extra option to specify if scrolling of the element is necessary, if it is already *fully* visible in container. In other words if element completely fits the view, then do nothing.

I think in some scenarios this is very ergonomic, as will reduce the number of scrolls and thus visual pressure on the user.

**Comment by flesler** [comment]
Hi @dmak, I think, given what you ask happens "before" calling the plugin and the fact that this plugin is parallel to $().animate(), I think this check should be done outside the plugin.

You can include a plugin that helps you make the check and avoid calling this plugin the element is already on screen.

I'll close this because I think it's out of the scope of the plugin
Thanks for taking the time to propose the feature

**Comment by dmak** [comment]
That is right: that can be done outside the plugin. However it requires the calculation of element height (including borders and margin) and calculating basically the scroll offset. After the computation is completed, the calling the plugin is not needed, as value for `scrollTop()` is already calculated.

**Comment by dmak** [comment]
Actually don't bother: I have decided to implement this function myself ([see result here](http://stackoverflow.com/a/37622507/267197)). Actually I first tried to improve `jquery.scrollTo()` but I found it too difficult as I need only vertical scrolling (x-axis).

**Comment by flesler** [comment]
What I COULD do is (maybe) move the code that calculates the final position, based on all the settings (offset, margin, etc), to a utility method that is exposed. This was the amount of code doesn't change but you can precalculate the final position, see if scroll or not and pass it directly to the plugin (or scrollTop())

**Comment by dmak** [comment]
Well, that's up to you. I have decided to stick to more light-weight solution which I can manage. In total it's about 50 lines, and I am not sure that connecting to some API will save _much_ coding.
