### ISSUE TITLE
Scroll element to top/bottom of the container depending on its initial location

### ISSUE THREAD

**Issue by dmak** [flesler/jquery.scrollTo#137]
I am not sure how to implement this feature using existing API (excuses if that is possible). I thought about `settings.scroll(function(elem, targ) {})` but it seems to be tricky to implement what I describe below.

Let's distinguish two different situations (I will bound only to y-axis for simplicity):
1. Element is above the viewport (so container needs to be scrolled upwards for it to become visible). In this case the element is scrolled to the top of the viewport (appears at the top of the container). This is current `scrollTo()` plugin behaviour.
2. Element is below the viewport (so container needs to be scrolled downwards for it to become visible). In this case the element is scrolled to the bottom of the viewport (appears at the bottom of the container). This is new feature.

Usecase: Minimise the time for scrolling to complete and thus improve user experience.

**Comment by flesler** [comment]
Closing this, you can ask on SO

**Comment by dmak** [comment]
Actually I have already [posted my own suggestion](https://stackoverflow.com/a/37622507/267197) after I've played with few libraries which provide this kind of functionality.
