### ISSUE TITLE
Scrolling back and forth on same anchor? Berserk mode!

### ISSUE THREAD

**Issue by katerlouis** [flesler/jquery.scrollTo#138]
Hard to explain, I've done a short screencast illustrating the problem:
https://www.dropbox.com/s/vo5mcb3ssyb9ymu/jQuery.scrollTo%20goes%20berserk.mov?dl=0

In short:
from one breakpoint to the other scrollTo goes berserk and I can't find out why.
700 and below it scrolls back and forth although the target element remains at same place.
701px and higher it works perfect.

Anchors jumping works as intended without scrollTo on every breakpoint.

When .rohstoff has `display: flex`, it works. But I can't have it a flexbox below 700px. 
The anchor (a[name]) doesnt get styled at all (screenshot below)

I tried scrollTo good'ol version 1.4.12 which done me good for so long and 2.1.2. Same behavior.
Latest Chrome, Safari and Firefox on OS X 10.11.5 also produce same behavior.
What is happening here? 

HTML example Layout
```html
<div class="rohstoff">
	<a name="fahrzeugsicherstellung"></a>
	<div class="title">
		<h1>Fahrzeugsicherstellung</h1>
	</div>

	<div class="slider-container">
		<div class="all-slides">
			<div class="slide"> ... </div>
			<div class="slide"> ... </div>
			<div class="slide"> ... </div>
		</div>
		<div class="pagination"> ... </div>
	</div>
</div>

```

jQuery
```js
$("a[href*='#']").on(ClickOrTap, function(e) {
	e.preventDefault(); // e.stopImmediatePropagation();
	var name = $(this).attr("href").replace("#", "");
	var $target = $("a[name='" + name + "']");
	$.scrollTo($target, { duration: 500, offset: 0, easing: "swing" });
});
```

Anchor element to scroll to styles
On every breakpoint the same
![d8be2c61-8eab-4422-b112-d17493a3abe7](https://cloud.githubusercontent.com/assets/1983382/16520059/bd21c268-3f8d-11e6-9289-eb12f0e20a2f.png)

**Comment by katerlouis** [comment]
Checking .offset() while scrolling around.
First 3 entries above 701px (working)
Last 2 entries below 700px (not working)

Do you have any explanation for this?

![5efe2554-4e81-41a9-b530-0d3afc75cc6c](https://cloud.githubusercontent.com/assets/1983382/16520223/0afa0120-3f8f-11e6-839f-757c6f0d4545.png)

**Comment by katerlouis** [comment]
Okay, the anchor needs to be a block? It worked as an inline-element before just fine :o
Although it is solved now I'd like to know your thoughts about this.

Thanks!

**Comment by flesler** [comment]
Hi @katerlouis, the positioning calculation is delegated to the native $().offset() method.
It's not likely something to fix in the plugin. Browsers do that kind of weird stuff.
You can try changing the jQuery version or the quirksMode

**Comment by katerlouis** [comment]
quirksMode?

**Comment by flesler** [comment]
Yes
