### ISSUE TITLE
Scrolling doesn't work on iOS when 'interrupt' is true

### ISSUE THREAD

**Issue by sarahmonster** [flesler/jquery.scrollTo#139]
I've discovered what I think is an issue with the library. Using hash links in iOS, scrolling doesn't work at all (the page doesn't jump down to the target at all) if `interrupt` is true. Once I set `interrupt` to false, the same code worked as expected.

Here's the code I'm using; it's more or less verbatim from the examples:

```
$( 'a[href^="#"]' ).click( function( e ) {
    e.preventDefault();
    $( window ).stop( true ).scrollTo( this.hash, { duration: 1000, margin: true, interrupt: true } );
});

// When we click on the "jump to recipe" link, find the recipe and scroll to it
$( '#smittenkitchen-jump-links' ).find( '.recipe-jump-link' ).click( function( e ) {
    e.preventDefault();
    var $recipe = $( this ).parents( 'article' ).find( '.entry-content' ).find( '.jetpack-recipe' );
    if ( 0 < $recipe.length ) {
        $( window ).stop( true ).scrollTo( $recipe, { duration: 1000, margin: true, interrupt: true } );
    }
});
```

**Comment by flesler** [comment]
Hi, can you try the [demo page](http://demos.flesler.com/jquery/scrollTo/) with the same device?
If it works, then it probably means there's something "special" in your page, otherwise, it might be a compatibility issue.

**Comment by sarahmonster** [comment]
I tried the demo, which seems to work on iOS. But when I test the same code, running in a pen so it isn't conflicting with anything else in the page, I'm having the same issue:

http://codepen.io/sarahmonster/pen/vKWgOA

Works on a desktop browser, doesn't work in iOS. Replicated both on an actual device and via the Simulator.

**Comment by davdenic** [comment]
I have the same issue and solved like this

`	$('.mouse-container').on('touchstart touchend', function() {
		$(window).scrollTo("#Content",1000,{interrupt:false, offset: -80});
	});
	$('.mouse-container').on('mousedown mouseup', function() {
		$(window).scrollTo("#Content",1000,{interrupt:true, offset: -80});
	});`

**Comment by flesler** [comment]
@sarahmonster can you confirm if that fixes the issue for you?
