### ISSUE TITLE
Scroll doesn't work smoothly with Safari

### ISSUE THREAD

**Issue by piyushkhemka** [flesler/jquery.scrollTo#141]
Hello

The scrolling works smoothly as intended in Chrome. However, in safari the scrolling is very laggy to the point where the site becomes unusable.

Is there a fix for safari, similar to something like this: [Simliar issue with Smooth Scroll](https://github.com/kswedberg/jquery-smooth-scroll/issues/29)

Here is how I am calling scrollTo in my custom js file.

```

$(function () {
    scrollS();
});

function scrollS() {
 $('.scroll-to, #navigation a').click(function (event) {
        event.preventDefault();
        var full_url = this.href;
        var parts = full_url.split("#");
        var trgt = parts[1];
        $('body').scrollTo($('#' + trgt), 800, {offset: -49});
```

**Comment by flesler** [comment]
Please reopen if you still see it with modern versions of everything

**Comment by jaburcodes** [comment]
still doesn't work on safari

**Comment by waldbach** [comment]
I have serious issues in Safari as well, works perfect on Chrome, Safari the scroll just stops too soon. The further away the element, the sooner the scroll just stops.

**Comment by waldbach** [comment]
Solved it, added height and width to element and container.
