### ISSUE TITLE
Fail to calculate maximum scrollpos with scaled content

### ISSUE THREAD

**Issue by Simon-Joker** [flesler/jquery.scrollTo#142]
```
$scrollTo.max = function(elem, axis) {
        var Dim = axis === 'x' ? 'Width' : 'Height',
            scroll = 'scroll'+Dim;

        if (!isWin(elem))
//e.g. $(elem).parent().css({transform:'scale(2,2)'});
//here ist the problem. 
//the property elem.scrolHeight contains the unscaled value (e.g.:100) and
//the jquery-function $(elem).height() will return the scaled height (e.g.:200)
            //return elem[scroll] - $(elem)[Dim.toLowerCase()]();   
//better way is use the property clientHeight
            return elem[scroll] - elem['client'+Dim];   

        var size = 'client' + Dim,
            doc = elem.ownerDocument || elem.document,
            html = doc.documentElement,
            body = doc.body;

        return Math.max(html[scroll], body[scroll]) - Math.min(html[size], body[size]);
};
```

**Comment by flesler** [comment]
Elements scaled with transforms are special. If I recall correctly, the scale doesn't even change the bounding box, the element for most things still takes the unscaled size.

Before changing that I need to make sure it doesn't break any other cases, otherwise I think this use case needs to be chosen to fail if it comes to choosing.

**Comment by KingSora** [comment]
hi!

To calculate the correct boundingbox of a transformed element use 
```javascript
element.getBoundingClientRect();
```
Every browser which supports transform supports this method.

Best regards,
Sora

**Comment by flesler** [comment]
@KingSora Thanks for the comment. I'll close the issue because it's not something I think the plugin should be doing.

**Comment by ggiacomo** [comment]
Hi there, is there any update or workaround to make it works with scaled content? Thanks

**Comment by flesler** [comment]
Update, there isn't. Workound, I suppose whenever you call this plugin. First use the method mentioned above and, with some math, you should get the values you need to pass in the `over` (or `offset`) option to account for the scaling.
