### ISSUE TITLE
Cannot use scrollTo when document is inside an iframe

### ISSUE THREAD

**Issue by AleCaste** [flesler/jquery.scrollTo#143]
Hello,
I have been using your excellent plugin for many years without a problem.
But today I loaded a webpage which makes use of your scrollTop plugin inside an iframe tag and I realized that when doing so, the scrollTop commands happening inside the iframe are totally ignored.

Is there any way of making scrollTop work when the document is inside an iframe or is this an impossible mission due to how iframes work in the browser?

Thanks a lot

**Comment by flesler** [comment]
Hi, we have some test HTML files (I deleted some recently) that test this kind of thing, last time I checked that was working.

It can be either something wrong in your implementation or a software version that hasn't been tested.
If you investigate further, please report your findings. If you provide a PR I'll review and merge.

Regards
