### ISSUE TITLE
Cannot read property 'propHooks' of undefined

### ISSUE THREAD

**Issue by BrianCohen** [flesler/jquery.scrollTo#144]
Error: Cannot read property 'propHooks' of undefined

Using JQuery 3.1.1

**Comment by bcharboneauiherb** [comment]
I too am experiencing this issue and I have tried multiple versions of jquery.

**Comment by flesler** [comment]
I updated http://demos.flesler.com/jquery/scrollTo to use jQuery 3.2.1 and everything's working fine.
Can you confirm if you still see this issue?

**Comment by BrianCohen** [comment]
I don't remember where I had this issue, impossible to recreate. But if I come across it again, I'll post back.

**Comment by flesler** [comment]
Ok please reopen if you do
