### ISSUE TITLE
Bouncing behavior on 3D parallax site

### ISSUE THREAD

**Issue by gbhojraj** [flesler/jquery.scrollTo#146]
I'm making a pure CSS parallax site.  I have an HTML page with the following format:

```
<div class="parallax">
    <div class="sub" id="one"> Content </div>
    <div class="sub" id="two"> Content </div>
</div>
```

And the following CSS rules (editing out background image rules):

```
* {
  margin: 0;
  padding: 0;
}

.parallax {
  height: 100vh;
  overflow-x: hidden;
  overflow-y: auto;
  -webkit-perspective: 1px;
  -webkit-perspective-origin: 100% 100%;
}

.sub {
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  padding: 100vh 0;
  -webkit-transform-origin: 100vw 100vh;
}

#one {
  -webkit-transform: translateZ(-1px) scale(2);
  transform: translateZ(-1px) scale(2);
}
```

In the console, if I run a command like:
$('.parallax').scrollTo(400, 600, {axis: 'y', onAfter: function(a, b){console.log('done');}});

I have this strange behavior where the screen will scroll down, "done" will print, and the screen will scroll back up to the top, then very slowly start scrolling down again. Is there any quick fix for this?

**Comment by flesler** [comment]
You should make this type of questions on a forum like StackOverflow, this section is mostly for bug reports and some feature requests
