### ISSUE TITLE
It just doesn't work on Android.

### ISSUE THREAD

**Issue by Jakkc** [flesler/jquery.scrollTo#153]
Title.

There are a few disparate conversations about it on the internet, but I've yet to find a solution anywhere.

Yet it seems to work on Android on the demo site.

This is surely an issue pretty much every user has come across? How come theres such little documentation on the matter?

**Comment by flesler** [comment]
Hi, the plugin is used by quite a lot of sites. It's probably not as extreme as in not working at all on Android, maybe you hit a certain problematic scenario that others did as well.

The plugin relies on jQuery core for the actual scrolling animation so, if it isn't working, it's likely that the content won't scroll with most plugins.

I don't have an Android myself. If you find a fix (or someone else does) please provide a PR and I'll review it
