### ISSUE TITLE
scrollTo not working depending on how I call it

### ISSUE THREAD

**Issue by sebmuller** [flesler/jquery.scrollTo#154]
I have an **index.html** file where I create the following variable like so:
`target = $('#portfolio23-inline1 div.inline-cont');`

Then, in my **site.js** file, I do a bunch of things and that's from where I call the function like so:
`target.scrollTo('#' + id, {duration:700,axis:"y",offset:0});`
This way, it works

But if I want to to it the folowing way, it doesn't:
`$('#portfolio23-inline1 div.inline-cont').scrollTo('#' + id, {duration:700,axis:"y",offset:0});`

I'd like to do it this way as I want to dynamically change the _portfolio23-inline1_ id that can be _portfolio26-inline1_ etc depending on the **id** variable value. I'd like something like:
`$('#portfolio' + id + '-inline1 div.inline-cont').scrollTo('#' + id, {duration:700,axis:"y",offset:0});`

Does somebody have an idea of what's going wrong with what I'm coding ?

Thanks a lot !

**Comment by flesler** [comment]
Hi @sebmuller, for getting help with your issues you should rather post on forums like StackOverflow, that will get you much more reach. GH issues are only to report concise bugs or requests for enhancements/features. I'm closing this
