### ISSUE TITLE
How to scroll with sticky nav on top..

### ISSUE THREAD

**Issue by inironnie** [flesler/jquery.scrollTo#156]
Hi there,

i've web structure like this

<container> <- sticky nav (height:100px)
</container>

<container> <- big banner
</container>

<container> <- content
    <docnav> < sticky too...
    <doccontent> <-here my problem
</container>

the problem is how i only scroll doccontent with set margintop of anchor 100px too (because i've
![1 default home]

 sticky nav on top..)

Please help me to find ways scroll anchor with sticky navigation menu.. 
really thankfull for your helping..

(https://user-images.githubusercontent.com/9944012/27365357-e7232cde-5669-11e7-84d5-715410c22025.jpg)
![2 the problem](https://user-images.githubusercontent.com/9944012/27365355-e71b2606-5669-11e7-9d64-ce58732c36da.jpg)
![3 my situation](https://user-images.githubusercontent.com/9944012/27365356-e722d78e-5669-11e7-802a-42b1039a95db.jpg)

**Comment by flesler** [comment]
You should make this type of questions on a forum like StackOverflow, this section is mostly for bug reports and some feature requests
