### ISSUE TITLE
jQuery dep has problematic version in package.json

### ISSUE THREAD

**Issue by jalooc** [flesler/jquery.scrollTo#159]
This notation: `"dependencies": { "jquery": ">=1.8" },` accepts also breaking versions (like 2.x, 3.x etc.), so it breaks semver security. It also creates problems when installing with yarn a package which has `jquery.scrollTo` as a dep:
```
$ yarn install --flat
yarn install v0.27.5
[1/4] Resolving packages...
info Unable to find a suitable version for "jquery", please choose one by typing one of the numbers below:
  1) "jquery@^2.2.2" which resolved to "2.2.4"
  2) "jquery@>=1.8" which resolved to "3.2.1"
```
https://github.com/geniuscarrier/webpack-boilerplate/issues/7

**Comment by flesler** [comment]
What do you mean by breaking versions? They break scrollTo or the fact that the major version changed?

**Comment by jalooc** [comment]
The second one, that it will install potentially breaking versions.

**Comment by flesler** [comment]
Would moving it to a `peerDependency` solve the issue for you?

**Comment by jalooc** [comment]
Not really, the best solution is just to stick to minor version in package.json, like: "^2.2.2"

**Comment by flesler** [comment]
That would lock the plugin to only one major version at a time, which is incorrect and undesired

**Comment by jalooc** [comment]
Well, I think it is correct, because if some breaking change in major version is incompatible with your code, then you break all of you users code. But it's ofc up to you
