### ISSUE TITLE
Not working in Chrome 61

### ISSUE THREAD

**Issue by shenbagadeviks** [flesler/jquery.scrollTo#162]
scrollTo is not working with the latest Chrome update. (Chrome 61)

**Comment by flesler** [comment]
I'm using Chrome 61.0.3163.79 on Windows 10, testing the demo site at http://demos.flesler.com/jquery/scrollTo/ and all the links work. It seems like it's something specific to the site you are working on

**Comment by nickcernis** [comment]
@shenbagadeviks Are you using the latest version of scrollTo on your site?

I saw the same issue with Chrome 61 until I updated to the latest versions:

- https://github.com/flesler/jquery.scrollTo/blob/master/jquery.scrollTo.min.js
- https://github.com/flesler/jquery.localScroll/blob/master/jquery.localScroll.min.js

**Comment by shenbagadeviks** [comment]
@nickcernis Thanks for the update. Yeah we were using older version.

**Comment by deviirmr** [comment]
> @shenbagadeviks Are you using the latest version of scrollTo on your site?
> 
> I saw the same issue with Chrome 61 until I updated to the latest versions:
> 
> * https://github.com/flesler/jquery.scrollTo/blob/master/jquery.scrollTo.min.js
> * https://github.com/flesler/jquery.localScroll/blob/master/jquery.localScroll.min.js

Yes you are right, after replacing old js files now its working in both Chrome and Firefox.
