### ISSUE TITLE
Scrolling from top of the page on History back button

### ISSUE THREAD

**Issue by thelar** [flesler/jquery.scrollTo#167]
Hi there,

I'm trying out scrollTo on a small woocommerce site where all my products are on a single page. I have got it scrolling nicely between products, up and down the page when I use the navigation based on a 'hashchange' event. However, when I hit the back button in my browser, instead of scrolling FROM the current product to the previous one, the browser jumps to the top of the page and animates down from there! Then having gone back a few times to previous products, when I use the forward button, instead of scrolling it starts to jump. This is happening in current versions of Chrome and Firefox.

Although I could live with this, my site is for an accessible audience and I would like to give them a seamless experience where the forward and back buttons scroll the page up and down in the same way that the on page navigation does. 

I was just wondering if anyone here had experience of this issue and whether there is a solution?

Many thanks
Kevin

**Comment by flesler** [comment]
Hey, maybe it's solvable combining other plugins to monitor history changes and some glue code. You should ask this on sites like StackOverflow, someone might suggest a good solution
