### ISSUE TITLE
Setting interrupt to true has no effect in Mozilla Firefox 57.0.4

### ISSUE THREAD

**Issue by UsernameUltra** [flesler/jquery.scrollTo#168]
This should enable user to stop the animation by scrolling, but animation just goes on until it's done( by the way, there is no such problem in Opera 50 and Chrome 63

**Comment by flesler** [comment]
Hi, can you confirm if it still happens with the latest version? and also (if you are now using one) with a newer version of FF?

**Comment by flesler** [comment]
I'm closing since it's been a while, feel free to re-open if you still see the problem
