### ISSUE TITLE
scrollTo getting stuck on chrome

### ISSUE THREAD

**Issue by benbyford** [flesler/jquery.scrollTo#170]
Strange behaviour i havent seen before on chrome. http://www.carolineleeming.com/

clicking a link should scroll you to top of the #page, which works on FF and Safari, but on chrome it moves up 50 px and stops, where ever you are.

Any guidance would be wonderful

**Comment by flesler** [comment]
Hi, for support requests, you should rather ask on sites like StackOverflow where many more people reply.
Cheers

**Comment by tmorehouse** [comment]
Appears that  this might be a new bug.  I have newer version of chrome not working with scrollTo, while older version of chrome (and all other browsers) still work.

**Comment by flesler** [comment]
If you can create a small example that reproduces, I can look into it.
Seems like a constant with chrome, things break, then start working again in a newer version though
