### ISSUE TITLE
can this plugin be used to scroll to the bottom of the div

### ISSUE THREAD

**Issue by eshiett1995** [flesler/jquery.scrollTo#172]
I have a div, but i have no idea of its width, can this plugin be used to scroll to the bottom of any particular div, if i dont know the height of the div ?

**Comment by flesler** [comment]
Hi, for "help" questions you should ask on sites like StackOverflow where many more people might reply to you

**Comment by sokollondon** [comment]
```js
$.scrollTo($('#d'), 500, {'offset':-$(window).height() + $('#d').height()});
```
