### ISSUE TITLE
On chrome, if "scroll-behavior: smooth", the duration acts like a delay instead of duration

### ISSUE THREAD

**Issue by mateus-r** [flesler/jquery.scrollTo#173]
Hi,
on Chrome  (73.0.3683.75), if I have scroll-behavior set to smooth on my css, the duration parameter only adds a delay to the scroll instead of changing the duration of the animation.

eg. 
`jQuery(window).scrollTo(document.getElementById(id), 500, {onAfter: function() { //function }});`
This will wait for 500ms, and then do a "regular chrome scroll", which isn't affected by duration.

I know i can just remove smooth scrolling on css, but on chrome and firefox it causes too much screen tearing/desync

Below is my script if it's needed:
```
var up = null;
var down = null;
scrollando = false;

function div(x) {
	
	switch(x.id) {
		case 's1':
			up = null;
			down = 's2';
			break;
		case 's2':
			up = 's1';
			down = 's3'
			break;
		case 's3':
			up = 's2';
			down ='s4';
			break;
		case 's4':
			up = 's3';
			down = null;
			break;
		default:
			up = null;
			down = null;
			break;
		}
}

window.addEventListener('wheel', function(e) {	
	
	e.preventDefault();
	

	if (e.deltaY < 0 && up && !scrollando) {	//if scrolling up && theres upper div && isn't in the middle of a scroll already
		scrollando = true;		
		jQuery(window).scrollTo(document.getElementById(up), 500, {complete: function() { 
				scrollando = false; 
		}});
		div(up);
	}
	
	if (e.deltaY > 0 && down && !scrollando) {
		scrollando = true;
		jQuery(window).scrollTo(document.getElementById(down), 500, {onAfter: function() { 
				scrollando = false; 
		}});
		div(down);
	}
}, { passive: false } );
```

**Comment by flesler** [comment]
Hi, I've never played around with `scroll-behavior: smooth` and this never came up before.
I'm not actively taking the long time it takes to reproduce and write fixes. If you find a potential fix or someone suggests somewhere (like StackOverflow) feel free to post it and we can review (or make a PR)
Thanks
