### ISSUE TITLE
Not working in Firefox

### ISSUE THREAD

**Issue by nikulnayi** [flesler/jquery.scrollTo#174]
scroll To is working well in chrome but not working in Firefox

**Comment by flesler** [comment]
This is certainly not actionable, I'll need a minimalistic demo that reproduces the issue in order to be able to test

**Comment by nikulnayi** [comment]
here is my website you may take look
check it in both the browser Chrome and Firefox

http://foodver.esy.es/

**Comment by flesler** [comment]
Hi, I don't offer support sadly. I don't have the time for it.
If you can figure the problem is reduce it to a very very minimalistic example I can take a look. You could ask for help in sites like StackOverflow as well
