### ISSUE TITLE
Cant get my website to work cross browser

### ISSUE THREAD

**Issue by Lugzyboy82** [flesler/jquery.scrollTo#176]
I have been struggling for a while trying to get my navbar to work. For some reason it doesn't work on chrome or android.
Im not sure if its a coding issue or if I need to update my scrollTo libraries. Im at a loss and out of ideas. I have read through the posts on here and sometimes updating the libraries can fix the problem. I am a novice at this and wouldn't know where to start or how to do this.
If somebody could help me, that would be great. The website is www.suresealservices.co.uk
Thank you in advance.

``<ul class="nav navbar-nav navbar-right">
	<li><a href="#home" class="smoothScroll">HOME</a></li>
	<li><a href="#service" class="smoothScroll">SERVICES</a></li>
	<li><a href="#about" class="smoothScroll">SOFTWASHING</a></li>
	<li><a href="#team" class="smoothScroll">NANO-TECH</a></li>
	<li><a href="#portfolio" class="smoothScroll">COMMERCIAL</a></li>
	<li><a href="#contact" class="smoothScroll">CONTACT</a></li>
</ul>

**Comment by Lugzyboy82** [comment]
``<div class="collapse navbar-collapse">
					<ul class="nav navbar-nav navbar-right">
						<li><a href="#home" class="smoothScroll">home</a></li>
						<li><a href="#service" class="smoothScroll">service</a></li>
						<li><a href="#about" class="smoothScroll">about</a></li>
						<li><a href="#team" class="smoothScroll">team</a></li>
						<li><a href="#portfolio" class="smoothScroll">portfolio</a></li>
						<li><a href="#contact" class="smoothScroll">contact</a></li>
					</ul>
				</div>

**Comment by Lugzyboy82** [comment]
<div class="collapse navbar-collapse">
	<ul class="nav navbar-nav navbar-right">
		<li><a href="#home" class="smoothScroll">home</a></li>
		<li><a href="#service" class="smoothScroll">service</a></li>
		<li><a href="#about" class="smoothScroll">about</a></li>
		<li><a href="#team" class="smoothScroll">team</a></li>
		<li><a href="#portfolio" class="smoothScroll">portfolio</a></li>
		<li><a href="#contact" class="smoothScroll">contact</a></li>
	</ul>
`</div>`

**Comment by Lugzyboy82** [comment]
> <div class="collapse navbar-collapse">
					<ul class="nav navbar-nav navbar-right">
						<li><a href="#home" class="smoothScroll">home</a></li>
						<li><a href="#service" class="smoothScroll">service</a></li>
						<li><a href="#about" class="smoothScroll">about</a></li>
						<li><a href="#team" class="smoothScroll">team</a></li>
						<li><a href="#portfolio" class="smoothScroll">portfolio</a></li>
						<li><a href="#contact" class="smoothScroll">contact</a></li>
					</ul>
				</div>

**Comment by flesler** [comment]
Hi, for support requests you should rather ask on sites like StackOverflow where a lot of users are watching and several will surely have time to review what you posted. I leave this only for proven bugs and some feature requests. Regards
