### ISSUE TITLE
initializing plugin using webpack

### ISSUE THREAD

**Issue by tacman** [flesler/jquery.scrollTo#177]
I'm having an issue initialing this plugin with webpack.

I've added jquery and the plugin via yarn, my script is simply:
```
const $ = require('jquery');
require('scrollto');
$('#error').scrollTo({top: '50%'});
```
This throw the error

```
TypeError: $.propHooks is undefined
```

I'm using jQuery 3.4, full version, and I can see that the animate functions exist.  I suspect the problem is related to the global jQuery object.  I've retried reordering the lines, and using import and require, but I'm missing something.  I've tried the suggestions at https://symfonycasts.com/screencast/webpack-encore-legacy/jquery-plugins, but can't figure it out.

Thanks.

**Comment by flesler** [comment]
Hi, I'm closing this. There hasn't been much changes lately but I think this is due to using an older version of  the plugin and an incompatible version of jQuery
