### ISSUE TITLE
Setting to align scrolled item (e.g to bottom)

### ISSUE THREAD

**Issue by kosmodisk** [flesler/jquery.scrollTo#180]
It would be good to have a setting to specify how scrollable item is aligned in container.

I have read this issue https://github.com/flesler/jquery.scrollTo/issues/172 but it is not quite it since this talks about the case where item is scrolled always to bottom but I think this thing needs also "auto" setting where item is scrolled to nearest edge, i.e to start when it is behind top/left edge and to end when it is behind bottom/right edge. It should respect also the case not to scroll when the target is already visible.

E.g **align**
* start - scrolls to starting edge (top or left depending on axis), default
* center
* end
* nearest (or "auto"?)
* { x: start/center/end/nearest, y: start/center/end/nearest }

**Comment by flesler** [comment]
if I'm understanding correctly, I think you can handle most of that with `offset` and `over`. Have you checked those out?

**Comment by kosmodisk** [comment]
Yes, I am aware of offset. But I cant see how "over" helps me.

But even if they can help me positioning target item, there is an issue of how to _not scroll_ if item is already visible?

**Comment by flesler** [comment]
@kosmodisk I understand the bit about not scrolling, my personal philosophy (with this plugin) was a build a good building block that does its bit well and can be combined. NOT scrolling happens before and the logic people could need for not scrolling varies greatly. So my decision for that, was that people should decide if it scrolls or not from "the outside". That is, there are incredible jQuery plugins to check if stuff is "above the fold", "below the fold", on screen, etc. 

I'd recommend, on that regard, to combine it whatever suits your specific needs.

As for `offset` + `over`, I haven't experimented but seems to me like this can be achieved with those. I'm not currently shipping my own code to this plugin, I (try to) reply to GH issues and review & accept PRs. If you want to provide a PR for that setting, I'll review it gladly
