### ISSUE TITLE
Small proposition to cdn doc

### ISSUE THREAD

**Issue by technos12** [flesler/jquery.scrollTo#186]
Hi, I just discovered your library which helps me in my project, thank you !

Just a small input for a thing that made me lost a bit of time :
In the documentation, you provide a CDN link
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery-scrollTo/2.1.3/jquery.scrollTo.min.js"></script>
But if the src is not starting with http:// or https:// is was not working, at least in Firefox.
I have simply rewritten to 
<script src="https://cdn.jsdelivr.net/npm/jquery.scrollto@2.1.3/jquery.scrollTo.min.js"></script>
and voilà, works like a charm.

Thank again for developing this, I wish you a nice day.

**Comment by flesler** [comment]
Protocol-less was the norm, since it uses whatever the page uses. But since HTTP is pretty much deprecated, your suggestion makes total sense and makes it less esoteric :+1:
