### ISSUE TITLE
How to scroll lists (ul or ol)?

### ISSUE THREAD

**Issue by mbaas2** [flesler/jquery.scrollTo#191]
(Disclaimer: _I must have misunderstood something - but ofc, I don't see what it is. So I apologize in advance for this silly question!_  😉)

I am trying to scroll the items of a `ul` to make a specific `li` visible - but I'm failing (see [this](https://codepen.io/MBaas/pen/JjmEBzw) Codepen).
What have I done wrong?

**Comment by flesler** [comment]
Hi, you should set `overflow: auto` on the parent to be scrolled. If that works and you can scroll manually, you should be able to scroll programmatically by calling the plugin. Make sure the element is the same that has the scrollbar.

Most like you'll put the `ul` inside a `div`, the `div` has `overflow: auto` and you call `$().scrollTo` on it. Your example is trying to scroll the `ul`, that doesn't have scrollbar. You could also scroll the `window` if you intended to move the whole screen
