### ISSUE TITLE
Scroll only if element is offscreen?

### ISSUE THREAD

**Issue by evbrew** [flesler/jquery.scrollTo#193]
Great plugin, nice work!
Is there an option to only scroll if part of the target element is outside the browser viewing window?
e.g.
I have buttons that can open sub-menus in a vertical scroll-able side panel.
If the button opens a sub panel and that panel has content off screen then i want to scroll it into view.
But if the button opens a sub panel and all the content is visible, then i don't want to do the scroll since that just moves the panel around on the user annoyingly.

**Comment by flesler** [comment]
The plugin doesn't include that, it's meant to do one thing and do it well. There are several plugins to detect if something is "above the fold", "below the fold" or on screen. You'll need to find a library like that and combine them

**Comment by evbrew** [comment]
All good, just wanted to make sure the option wasn't already buried somewhere in all of the possible setting options ;-)
For anyone who comes later looking for the same thing, i found this small utility function that worked great even for more complex page layout cases.

https://gomakethings.com/how-to-check-if-any-part-of-an-element-is-out-of-the-viewport-with-vanilla-js/

> /*!
>  * Check if an element is out of the viewport
>  * (c) 2018 Chris Ferdinandi, MIT License, https://gomakethings.com
>  * @param  {Node}  elem The element to check
>  * @return {Object}     A set of booleans for each side of the element
>  */
> var isOutOfViewport = function (elem) {
> 
> 	// Get element's bounding
> 	var bounding = elem.getBoundingClientRect();
> 
> 	// Check if it's out of the viewport on each side
> 	var out = {};
> 	out.top = bounding.top < 0;
> 	out.left = bounding.left < 0;
> 	out.bottom = bounding.bottom > (window.innerHeight || document.documentElement.clientHeight);
> 	out.right = bounding.right > (window.innerWidth || document.documentElement.clientWidth);
> 	out.any = out.top || out.left || out.bottom || out.right;
> 	out.all = out.top && out.left && out.bottom && out.right;
> 
> 	return out;
> };
