### ISSUE TITLE
Option for not scrolling parent if child is still in view?

### ISSUE THREAD

**Issue by andrewchch** [flesler/jquery.scrollTo#2]
Hi there,

Your plugin is great, but I wonder if it would be possible, when scrolling a parent to a child element, to not scroll the parent if the child is still in view. When using the plugin to navigate down a scrolling dropdown menu via the keyboard you currently get the unnatural behaviour that the currently selected item stays at the top of the portion of the list in view - this works but it looks kind of odd when you compare it to standard scrolling behaviour on other elements.  

Any thoughts?

Cheers, Andrew.

**Comment by kellyelton** [comment]
Actually I was hoping for this as well.

**Comment by flesler** [comment]
I get it, I still think the right way to go is to combine this plugin with either another plugin that does what you need (I know there are) or just whip those 3-4 lines of code yourself or look them up on Google and combine it with scrollTo.
It's too big and unrelated to consider adding it to scrollTo.
Sorry
