### ISSUE TITLE
$.scrollTo.max calculation incorrect if both scrollbars visible

### ISSUE THREAD

**Issue by slaneyrw** [flesler/jquery.scrollTo#52]
Using Chrome 29.x, haven't testing in other browsers.

On your demo page (http://flesler.com/jquery/scrollTo/), the first scroll section $('#pane-target') has a max scrollLeft of 1011, but $.scrollTo.max returns 994.

The discrepancy 17px, the width of the scrollbar.

**Comment by gregblass** [comment]
Noticing this as well.
