### ISSUE TITLE
When user tries to scroll mid-animation, flickering occurs as scrollTo fights the scrollbar

### ISSUE THREAD

**Issue by gregplaysguitar** [flesler/jquery.scrollTo#53]
There are two possible solutions - either 1) ignore user scrolling until the animation is complete, or 2) cancel the animation so the user regains control. I'm not sure how easy 1) would be to implement, but 2) is very simple, as the following function demonstrates:

    function polite_scroll_to(val, duration, callback) {
        /* scrolls body to a value, without fighting the user if they
           try to scroll in the middle of the animation. */
        
        var auto_scroll = false;
        
        function stop_scroll() {
            if (!auto_scroll) {
                $("html, body").stop(true, false);
            }
        };
        $(window).on('scroll', stop_scroll);
    
        $("html, body").animate({
            scrollTop: val
        }, {
            duration: duration,
            step: function() {
                auto_scroll = true;
                $(window).one('scroll', function() {
                    auto_scroll = false;
                });
            },
            complete: function() {
                callback && callback();
            },
            always: function() {
                $(window).off('scroll', stop_scroll);
            }
        });
    
    };

**Comment by flesler** [comment]
Hi, I will try the approach mentioned on #67.
This issue is older but I'll close it as dup and proceed on the other one.
Thanks

**Comment by flesler** [comment]
This is implemented. To cancel on user scroll pass `{interrupt:true}`, if you want a callback that is called when the scroll is interrupted, you can pass a `fail` callback that is provided natively by jQuery. You can check the demo I updated it with an example of both settings.
