### ISSUE TITLE
Add option to stop animation if the user natively scrolled

### ISSUE THREAD

**Issue by satazor** [flesler/jquery.scrollTo#67]
It would be cool to have an `interrupt` option. If set to true, it will interrupt the animation if the user scrolled while it was animating. If you agree with it, I can make a quick PR with it added.

**Comment by flesler** [comment]
This is implemented. To cancel on user scroll pass `{interrupt:true}`, if you want a callback that is called when the scroll is interrupted, you can pass a `fail` callback that is provided natively by jQuery. You can check the demo I updated it with an example of both settings.
