### ISSUE TITLE
Add option that allows to proceed or not with the animation after calculating the final scroll positions

### ISSUE THREAD

**Issue by satazor** [flesler/jquery.scrollTo#68]
Unfortunately jquery waits for the whole `duration` before calling the `finish` callback. For instance, if you do `el.animate({ width: 100 }, 1000, finish)`, jquery will call the `finish` function always after 1000ms, even if the `width` is already 100.
Because scrollTo uses `animate` it has also this behaviour. I have a page where I scroll to an element when the user clicks a tab, but I don't want to wait for the whole duration if the scroll position is already on the target.

To prevent this, along with some more flexibility, we could add a `pre` option that is basically a function that is called before the animation (hence pre), that should return `true`/`false`. If `false` is returned, the animation won't take place. The `pre` function will be called with the final calculated properties.

Usage to solve the problem describe above:

```js
el.scrollTo(target, 1000, {
  pre: function (el, target, prop) {
      return prop.scrollTop !== el.scrollTop(); 
  }
});
```

We could do more complex validation with the `pre` option and I think it would be a good addition. Let me know if you agree and I will make a PR.

**Comment by flesler** [comment]
Actually I gave this a second thought and I like your idea of separating both parts.
I'll try to get this done once I finish with #101, #107 and related.

**Comment by satazor** [comment]
Thats good! Thanks

**Comment by flesler** [comment]
Hi @satazor, now that you have access to every [$().animate() setting](http://api.jquery.com/animate/) (since 2.0), you should be able to solve this using the `start()` callback. It receives a promise which has the element being scrolled.
Let me know if this what you needed then, feel free to close this if you do.

**Comment by satazor** [comment]
I will definitively upgrade to 2.0 and see how it goes, thanks for you work! Will give feedback as soon as possible.
