### ISSUE TITLE
[bug] Scroll doesn't work in Chrome Canary (38.0.2082.0 canary 64-bit)

### ISSUE THREAD

**Issue by fabdrol** [flesler/jquery.scrollTo#85]
**Problematic code:**
```javascript
var sTop = ((index * wheight) + 'px'); // e.g. 1604px 
$(document).scrollTo(sTop, this.scrollSpeed) // this.scrollSpeed = 300
```

**Versions:**
* Platform: OS X 10.9.3 build 13D65
* Browser: 38.0.2082.0 canary 64-bit

*The problem doesn't occur in the normal version of Chrome (35.0.1916.153)*

**Comment by flesler** [comment]
Following up with this on #101
Closing as duplicate, please chime in on the other issue to help troubleshoot this.
Thanks
