### ISSUE TITLE
Requirejs optimizer error: Mismatched anonymous define() module

### ISSUE THREAD

**Issue by bbone87** [flesler/jquery.scrollTo#91]
The current AMD implementation cause issues with the requirejs optimizer. The culprit appears to be the lack of a module name resulting in the common [Mismatched anonymous define() module error](http://requirejs.org/docs/errors.html#mismatch) after optimization.

Currently, I'm reverting to v1.4.12 which resolves this issue since the AMD implementation was slightly different prior to the change at 45e3ea2e7d3e3edda6e079b21cbff60cdf40f0b0

Is there a way to switch back to the AMD format used in v1.4.12 and still incorporate the changes implemented in v1.4.13?

**Comment by ChetanGoti** [comment]
Thanks @gpgekko I faced same issue when using optimizer and it saved me.

**Comment by flesler** [comment]
Hi, I changed the initialization code, now the warning should be gone. I like it better now too.
I pushed to master but haven't releases or published to NPM, can you test 2.1.1 and see that it works correctly with AMD and that the warning is gone? remember to test the minified version as well where the warning arises.
Thanks

**Comment by daverodriguez** [comment]
I ran into this issue today and confirmed that 2.1.1 fixes the problem. Thank you!

**Comment by flesler** [comment]
Thanks for confirming

**Comment by sssilver** [comment]
When will this be pushed to NPM?

**Comment by flesler** [comment]
I forgot to release it (or thought the change was too small, I don't remember), I just did.

Thanks
