### ISSUE TITLE
Confusion over whether to use documentElement or body as scroll target in recent chrome

### ISSUE THREAD

**Issue by mgravell** [flesler/jquery.scrollTo#92]
From chrome 33 onwards, there is confusion over whether body or documentElement should be the preferred scroll target, not body - at one point it emitted warnings, but that has now stopped. However, in those versions of chrome, if the 

chrome://flags/#enable-experimental-web-platform-features

flag is enabled, then scrolling totally breaks (document.body.scrollTop is always 0). Changing to documentElement as the scroll target: works.

See also: https://code.google.com/p/chromium/issues/detail?id=342307

edit: there is also a suggestion that the behavior depends on whether strict mode is enabled. Fun!

**Comment by flesler** [comment]
Following up with this on #101
Closing as duplicate, please chime in on the other issue to help troubleshoot this.
Thanks
